import { createFileRoute, notFound, redirect } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { BarChart3, ExternalLink, Link2, Loader2, Users } from "lucide-react";
import { SiteLayout } from "@/components/site/SiteLayout";
import { useAuth } from "@/contexts/AuthContext";
import { supabase, isSupabaseConfigured } from "@/integrations/supabase/client";
import { checkPanelAccess, fetchCollaboratorDashboard } from "@/lib/analytics.functions";

export const Route = createFileRoute("/admin/collaborators")({
  ssr: false,
  beforeLoad: async () => {
    if (!isSupabaseConfigured || !supabase) throw notFound();
    const { data } = await supabase.auth.getSession();
    const accessToken = data.session?.access_token;
    if (!accessToken) throw redirect({ to: "/auth", search: { redirect: "/admin/collaborators" } });
    try {
      const access = await checkPanelAccess({ data: { accessToken } });
      if (!access.admin && !access.collaborator) throw notFound();
    } catch {
      throw notFound();
    }
  },
  head: () => ({
    meta: [
      { title: "Collaborator dashboard — Editly Store" },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
  component: CollaboratorDashboard,
});

const inr = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;

function Metric({ icon: Icon, label, value, hint }: { icon: typeof Users; label: string; value: string; hint: string }) {
  return (
    <div className="glass rounded-3xl p-5">
      <div className="flex items-center gap-2 text-muted-foreground">
        <Icon className="size-4" strokeWidth={1.8} />
        <span className="text-xs font-semibold uppercase tracking-wider">{label}</span>
      </div>
      <p className="mt-3 font-display text-3xl font-extrabold text-ink">{value}</p>
      <p className="mt-1 text-xs text-muted-foreground">{hint}</p>
    </div>
  );
}

function CollaboratorDashboard() {
  const { session } = useAuth();
  const accessToken = session?.access_token;
  const { data, isLoading, error } = useQuery({
    queryKey: ["collaborator-dashboard", accessToken ?? ""],
    queryFn: () => fetchCollaboratorDashboard({ data: { accessToken } }),
    staleTime: 15_000,
    refetchInterval: 30_000,
    refetchOnWindowFocus: true,
  });

  return (
    <SiteLayout dark>
      <section className="mx-auto max-w-[1400px] px-6 pb-24 lg:px-12">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Partner analytics</p>
            <h1 className="mt-2 font-display text-[clamp(2rem,4vw,3.4rem)] font-extrabold text-ink">Your collaborator dashboard</h1>
            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">Track visitors and completed sales generated by every collaborator link assigned to your account.</p>
          </div>
          <div className="rounded-full bg-white/55 px-4 py-2 text-xs font-semibold text-ink">Auto-updates every 30 seconds</div>
        </div>

        {isLoading ? (
          <div className="flex min-h-[40vh] items-center justify-center"><Loader2 className="size-6 animate-spin text-ink/60" /></div>
        ) : error || !data ? (
          <div className="glass mt-8 rounded-4xl p-8 text-sm text-muted-foreground">Your collaborator access is not active yet.</div>
        ) : (
          <>
            <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              <Metric icon={Users} label="Visitors" value={data.totals.visitors.toLocaleString("en-IN")} hint={`${data.totals.page_views.toLocaleString("en-IN")} page views`} />
              <Metric icon={BarChart3} label="Sales" value={data.totals.sales.toLocaleString("en-IN")} hint="Completed orders" />
              <Metric icon={BarChart3} label="Revenue" value={inr(data.totals.revenue)} hint="Attributed revenue" />
              <Metric icon={Link2} label="Active links" value={String(data.links.filter((link) => link.active).length)} hint={`${data.links.length} total links`} />
            </div>

            <div className="mt-8 grid gap-6 lg:grid-cols-2">
              {data.links.map((link) => (
                <article key={link.id} className="glass rounded-4xl p-7">
                  <div className="flex items-start justify-between gap-4">
                    <div className="min-w-0">
                      <h2 className="truncate font-display text-xl font-extrabold text-ink">{link.name}</h2>
                      <p className="mt-1 truncate text-xs text-muted-foreground">{link.email}</p>
                    </div>
                    <span className={`rounded-full px-3 py-1 text-xs font-bold ${link.active ? "bg-accent text-accent-foreground" : "bg-ink/10 text-ink/60"}`}>{link.active ? "Active" : "Paused"}</span>
                  </div>
                  <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
                    <div className="rounded-2xl bg-white/55 p-4"><p className="text-xs text-muted-foreground">Visitors</p><p className="mt-1 font-display text-xl font-bold text-ink">{link.visitors}</p></div>
                    <div className="rounded-2xl bg-white/55 p-4"><p className="text-xs text-muted-foreground">Views</p><p className="mt-1 font-display text-xl font-bold text-ink">{link.page_views}</p></div>
                    <div className="rounded-2xl bg-white/55 p-4"><p className="text-xs text-muted-foreground">Sales</p><p className="mt-1 font-display text-xl font-bold text-ink">{link.sales}</p></div>
                    <div className="rounded-2xl bg-white/55 p-4"><p className="text-xs text-muted-foreground">Revenue</p><p className="mt-1 font-display text-xl font-bold text-ink">{inr(link.revenue)}</p></div>
                  </div>
                  <a href={link.url} target="_blank" rel="noreferrer" className="mt-5 flex items-center justify-between gap-3 rounded-2xl bg-white/55 px-4 py-3 text-xs font-semibold text-ink transition-colors hover:bg-white/80">
                    <span className="truncate">{window.location.origin}{link.url}</span><ExternalLink className="size-4 shrink-0" />
                  </a>
                </article>
              ))}
            </div>
          </>
        )}
      </section>
    </SiteLayout>
  );
}
